[CARMAN-230] Create Readme
dan-chez/car_manager_ui pull request #14
Opened 2024-08-26 23:36 UTC by DAArbelaez

## Jira ticket
[CARMAN-230](https://danchez.atlassian.net/browse/CARMAN-230)

### Description
Create Readme.

Online Readme preview tool: https://markdownlivepreview.com/

### Evidence
Screenshots or videos of the app with the new features.

### Depends on
Link to pull requests that are needed for this PR. If this PR depends on other PR, please add Don’t merge label.

2024-08-26 23:51 UTC, dan-chez reviewed
We need to add how to implement the package, the link where it's storaged and is apache 2.0 the selected license type?

2024-09-02 14:39 UTC, dan-chez requested changes

2024-09-02 14:39 UTC, dan-chez commented on README.md
> +**Car Manager UI** is a library of graphical components designed for the Car Manager application. This library provides a collection of widgets and UI elements that make it easy to create vehicle man
In `is a library of graphical components designed`
Wouldn't it be better to use "UI components" instead of "graphical components"?

2024-09-02 14:39 UTC, dan-chez commented on README.md
> +**Car Manager UI** is a library of graphical components designed for the Car Manager application. This library provides a collection of widgets and UI elements that make it easy to create vehicle man
In `This library provides a collection of widgets and UI elements that make it easy to create vehicle management applications with Flutter.`
That makes it easy to implement and reuse widgets. Something like that, don't you think? To not leave it for the development of that specific type of applications

2024-09-02 14:39 UTC, dan-chez commented on README.md
> +### Depend on it
Is this useful?

2024-09-02 14:39 UTC, dan-chez commented on README.md
> +  car_manager_ui: ^0.0.1
I think we should leave a placeholder to use latest version instead of leaving a hardcoded one here

2024-09-02 14:39 UTC, dan-chez commented on README.md
> +This project is licensed under the Apache License 2.0. See the LICENSE file for more details.
![image](https://github.com/user-attachments/assets/6402c2e5-1418-466e-8085-f15330638508)
Wouldn't it be better to put something like this?

2024-09-04 02:22 UTC, Danteurus commented on README.md
> +With Flutter:
This line seems incomplete without the one above it. It should likely read something like: 'Run this command with Flutter:'

2024-09-04 02:24 UTC, Danteurus commented on README.md
> +```
These are the steps to install the package. It would be clearer if the steps were numbered.

2024-09-04 02:27 UTC, Danteurus commented on README.md
> +Use this package as a library in your Flutter project.
There should be a clearer introduction to the installation process. Something like: 'To use this package as a library in your Flutter project, follow these steps.

2024-09-04 02:29 UTC, Danteurus commented on README.md
> +[Apache 2.0 License](https://www.apache.org/licenses/LICENSE-2.0)
This isn't mandatory, but the license could be shown as a list. Since there's currently only one license, it's not strictly necessary.

2024-09-04 02:34 UTC, Danteurus reviewed
The README is generally well done, but there are a few areas that could benefit from improvement. For example, using ordered lists would make the steps clearer and easier to follow. Additionally, some sections might be enhanced with more precise grammar and proper punctuation. These adjustments would help improve the overall readability and clarity of the document.

2024-09-04 19:16 UTC, dan-chez commented on README.md
> +```
This isn't really a step; it's just how the package is imported. Maybe 'Import it' is unnecessary. Just 'Now in your Dart code, you can use:' would be sufficient

2024-09-04 19:16 UTC, dan-chez commented on README.md
> +Use this package as a library in your Flutter project.
Maybe this line is not necessary

2024-09-04 19:18 UTC, dan-chez commented on README.md
> +[Apache 2.0 License](https://www.apache.org/licenses/LICENSE-2.0)
It's fine as it is now. It will always be just one license

2024-09-05 23:46 UTC, dan-chez approved these changes
Good job! 🚀

2024-09-12 00:43 UTC, Danteurus approved these changes
LG

2024-09-12 15:04 UTC, merged