[CARMAN-213] Move Page Title To Package
dan-chez/car_manager_ui pull request #8
Opened 2024-08-08 15:35 UTC by DAArbelaez

## Jira ticket
[CARMAN-213](https://danchez.atlassian.net/browse/CARMAN-213)

### Description
Move CMPageTitle widget to package.

### Evidence
![WhatsApp Image 2024-08-08 at 10 31 57 AM](https://github.com/user-attachments/assets/99108e66-ee83-4f1d-932f-4cbf6e489df6)

### Depends on
Link to pull requests that are needed for this PR. If this PR depends on other PR, please add Don’t merge label.

2024-08-10 15:16 UTC, dan-chez requested changes

2024-08-10 15:16 UTC, dan-chez commented on lib/src/components/page_title/page_title.dart
> +          if (showBottomDivider) kPrimaryDivider
Can we use Visibility widget please. Just to keep the same pattern for these cases

2024-08-10 15:16 UTC, dan-chez commented on lib/src/components/page_title/page_title.dart
> +class CMPageTitle extends StatelessWidget {
Should we keep calling this CMPageTitle or just PageTitle?

2024-08-10 15:16 UTC, dan-chez commented on lib/src/components/page_title/page_title.dart
> +class CMPageTitle extends StatelessWidget {
Class name is page_title...

2024-08-10 15:16 UTC, dan-chez commented on lib/src/constants/text_constants.dart
> +const kSubtitleTextStyle = TextStyle(
Are these styles for buttons?

2024-08-12 12:00 UTC, DAArbelaez commented on lib/src/components/page_title/page_title.dart
> +class CMPageTitle extends StatelessWidget {
cm... is fine.

2024-08-12 23:24 UTC, dan-chez approved these changes

2024-08-12 23:24 UTC, merged